# Generated by Django 3.1.3 on 2024-03-26 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='이름')),
                ('join_Date', models.DateTimeField(verbose_name='가입날짜')),
                ('birth_date', models.DateTimeField(verbose_name='생일')),
                ('level', models.CharField(choices=[('junior', '주니어'), ('student', '학생'), ('professor', '교수님'), ('god', '신')], default='junior', max_length=10)),
                ('sex', models.CharField(choices=[('M', 'Man'), ('W', 'Woman')], max_length=1)),
            ],
        ),
    ]
